#spring.main.web-application-type=none
server:
  port: 8082




keycloak:
  realm: demo_realm
  #  the client-id of the application, required;
  resource: web
  auth-server-url: http://127.0.0.1:8080/auth
  ssl-required: external
  credentials:
    secret: 11111111-1111-1111-1111-111111111111
  use-resource-role-mappings: true