#spring.main.web-application-type=none
server:
  port: 8082



  error:
    whitelabel:
      enabled: true

keycloak:
  realm: demo_realm
  #  the client-id of the application, required;
  resource: web
  auth-server-url: http://127.0.0.1:8080/auth
  # use-resource-role-mappings: true
  public-client: true

  principal-attribute: preferred_username

spring:
  main:
    allow-bean-definition-overriding: true

logging:
  level:
    org:
      springframework:
        security=DEBUG:

