#spring.main.web-application-type=none
server:
  port: 8099

  error:
    whitelabel:
      enabled: false

keycloak:
  realm: web_premission_realm
  resource: web_premission_client
  auth-server-url: http://127.0.0.1:8080/auth
  # use-resource-role-mappings: true
  public-client: false
  principal-attribute: preferred_username
  credentials:
    secret: ac63dee2-5382-448b-8b02-cfb76011acf7
  policy-enforcer-config:
    enforcement-mode: ENFORCING


spring:
  main:
    allow-bean-definition-overriding: true

logging:
  level:
    org:
      springframework:
        security: DEBUG
        

