server:
  port: 8086

spring:
  main:
    allow-bean-definition-overriding: true
  
keycloak:
  realm: demo_realm
  #  the client-id of the application, required;
  resource: service2
  auth-server-url: http://127.0.0.1:8080/auth
  # use-resource-role-mappings: true
  public-client: false

  principal-attribute: preferred_username  